fix : add network type inside `getinfo`
vincenzopalazzo/lampo.rs pull request #188
Opened 2024-03-06 00:56 UTC by Harshit933

We simply get the network from `conf` inside the `CoreWalletManager`. Thus, adding a function inside `CoreWalletManager` to return the chain of network the wallet is built upon.

fixes #183

2024-03-06 09:31 UTC, vincenzopalazzo requested changes
Thanks for this, but I think you can access the network directory from the lampo configuration that it is inside the lampod struct?

Or I am missing something?

2024-03-06 09:31 UTC, vincenzopalazzo commented on lampod/src/ln/inventory_manager.rs
> +                    .unwrap();
why did we need to unwrap?

2024-03-06 09:31 UTC, vincenzopalazzo commented on lampod/src/ln/channel_manager.rs
> +    }
Why?

2024-03-06 18:51 UTC, Harshit933 commented
> Thanks for this, but I think you can access the network directory from the lampo configuration that it is inside the lampod struct?
> 
> Or I am missing something?

Actually I missed to see conf inside `LampoChannelManager`. Thanks for the review.

2024-03-06 19:32 UTC, vincenzopalazzo requested changes
we can still do better 😄

2024-03-06 19:32 UTC, vincenzopalazzo commented on lampod/src/ln/inventory_manager.rs
> +                let chain = self.channel_manager.conf().network.to_string();
```suggestion
                let chain = self.channel_manager.conf.network.to_string();
```

if you can not do that, try `pub (crate) conf`

2024-03-06 19:32 UTC, vincenzopalazzo commented on lampod/src/ln/channel_manager.rs
> +    }
imho we do not need it :)

2024-03-07 10:35 UTC, vincenzopalazzo approved these changes
LGMT, thanks

2024-03-07 10:35 UTC, merged